--
-- PostgreSQL database dump
--

\restrict FPAFPCh3j3Y70FPhLtgCZNWekJZUhMVkQMo0AuiS9BRjFdwUGmLYkzP9xMVSulY

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: departments; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.departments (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT departments_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.departments OWNER TO appuser;

--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_tasks; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.employee_tasks (
    id bigint NOT NULL,
    status character varying(255) NOT NULL,
    employee_id bigint NOT NULL,
    task_id bigint NOT NULL,
    CONSTRAINT employee_tasks_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying])::text[])))
);


ALTER TABLE public.employee_tasks OWNER TO appuser;

--
-- Name: employee_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.employee_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.employees (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    department_id bigint,
    CONSTRAINT employees_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.employees OWNER TO appuser;

--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.tasks (
    id bigint NOT NULL,
    duration integer NOT NULL,
    end_date date NOT NULL,
    name character varying(255) NOT NULL,
    start_date date NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT tasks_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying])::text[])))
);


ALTER TABLE public.tasks OWNER TO appuser;

--
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: employee_tasks employee_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.employee_tasks
    ADD CONSTRAINT employee_tasks_pkey PRIMARY KEY (id);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- Name: employee_tasks uk2nfrew2c0flv8veu1rq4ixn7m; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.employee_tasks
    ADD CONSTRAINT uk2nfrew2c0flv8veu1rq4ixn7m UNIQUE (employee_id, task_id);


--
-- Name: employees ukj9xgmd0ya5jmus09o0b8pqrpb; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT ukj9xgmd0ya5jmus09o0b8pqrpb UNIQUE (email);


--
-- Name: employee_tasks fk8f1s5kqk7lg5gmjlp0u84y7u; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.employee_tasks
    ADD CONSTRAINT fk8f1s5kqk7lg5gmjlp0u84y7u FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: employee_tasks fkbyismgfcs3xjfh6tr2axqgyus; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.employee_tasks
    ADD CONSTRAINT fkbyismgfcs3xjfh6tr2axqgyus FOREIGN KEY (task_id) REFERENCES public.tasks(id);


--
-- Name: employees fkgy4qe3dnqrm3ktd76sxp7n4c2; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fkgy4qe3dnqrm3ktd76sxp7n4c2 FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- PostgreSQL database dump complete
--

\unrestrict FPAFPCh3j3Y70FPhLtgCZNWekJZUhMVkQMo0AuiS9BRjFdwUGmLYkzP9xMVSulY

